### ISSUE TITLE
Break up the non-SRP files

### ISSUE THREAD

**Issue by fosrias** [refractproject/minim#15]
Better to have multiple files and associated tests to figure out what is going on and then tests and files only have one reason to change.

**Comment by fosrias** [comment]
BTW, happy to do this. Just let me know you concur.

**Comment by smizell** [comment]
That is a goal. I tried this out earlier today and got into an issue with
circular dependencies. I need the factory you mentioned recently to make
this work

**Comment by smizell** [comment]
Also, forgot to mention, feel free to solve this if you were interested! I
think if you solve the factory issue, this will be simple.

**Comment by smizell** [comment]
I think this should include these things:
- Break up actual code
- Break up tests around code, and refactor most Array tests to be Collection tests
- Update README to describe Collections instead of Arrays and say Arrays and Objects have all the functionality of Collection (because it's a subtype)

**Comment by fosrias** [comment]
Yeah. The whole collection thing was more mental effort than I wanted to put in to understand given it all being lumped together. 

:+1: on all the proposed changes.

**Comment by smizell** [comment]
This can be handled by proposal of #22
