### ISSUE TITLE
Hierarchy

### ISSUE THREAD

**Issue by smizell** [refractproject/minim#17]
Elements should know of their children and their parents. 

Which brings me to a question I have. An `ObjectType` is basically a collection of `PropertyType` elements (which are essentially key-value pairs). To have the same format, and potentially help in future features, should `ArrayType` collections consist of some kind of `IndexType` that instead of having a key, it has an index. 

Reason being, an element needs to know where it is in the tree of elements, and without this having an explicit element (like `IndexType`), it would need to know the index for itself as well. If it did have this `IndexType`, it could know the array that it is in plus it's location without storing that.

Hope that makes sense.

@fosrias @zdne

**Comment by fosrias** [comment]
Hm. Not sure that an element needs to know its parent. Why? It introduces unnecessary coupling doesn’t it?

**Comment by smizell** [comment]
The benefit would be that you could pass around parts of the element tree and still know the context of that element. It would also allow for more complex lookups, like finding all elements with such-and-such attribute where the parent element is of such-and-such type.

**Comment by fosrias** [comment]
I am not sure this should be accomdated but the structure, but rather every element just having a parent property that is dependency injected when instantiating the wrapping class, no?

**Comment by smizell** [comment]
@fosrias Exactly. This parent relationship will not be handled by the Refract data structure, but rather by Minim. It is internal to element instance.

**Comment by kylef** [comment]
This was solved by #141.
