### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by smizell** [refractproject/minim#18]
Methods should have comments that describe the input parameters and what is returned.

Maybe use [Codo](https://github.com/coffeedoc/codo).

**Comment by fosrias** [comment]
Are you committed to staying with coffee script. There is also JSDoc and https://github.com/terryweiss/docstrap https://github.com/terryweiss/docstrap

**Comment by smizell** [comment]
I think this should go to ES6 eventually, maybe sooner than later. Mainly because:
1. This really needs the idea of classes to work (and extending those classes)
2. I don't think we should create our own class system, like Backbone or React (which React is moving away from)

**Comment by smizell** [comment]
So with that said, probably best to wait on this set up until it is moved to ES6.

**Comment by smizell** [comment]
Sticking with CS for the foreseeable future.
