### ISSUE TITLE
Convenience Methods

### ISSUE THREAD

**Issue by smizell** [refractproject/minim#25]
In reading [this utility code](https://github.com/apiaryio/fury.js/blob/master/src/refract/util.es6), it may be helpful to provide convenience methods for better filtering. I think the utility code there is moving toward a structured way to query the tree, which I think we want to avoid at the moment. Using pure JS code is preferred. This means we need some better convenience methods.

For collections:
- [x] `.getById()` takes a string and returns the first element found with ID in entire tree
- [x] ~~`.filterByClass()` returns collection of elements where class matches given class name. Searches entire tree.~~

For items:
- [x] `.getClass()` returns an array of classes (or should it be collection?) (or `.classList()` or `.classes()`)
- [x] `.getId()` returns the ID of the element (undefined if not found) (or `.id()`)
- [x] `.withClass()` takes a string and returns true/false depending on if element has the class name given. Should also take an `options` argument where you can do things like `ignoreCase: true`.
- [x] `.hasClass()` returns true/false if element has classes
- [x] `.withId()` takes a string and returns true/false if the element has matching `meta.id`
- [x] `.hasId()` return true/false if element has an ID
- [x] `.withName()` takes a string and returns true/false if the element has matching `meta.name` (do we have a better name for this function?) Should take `options` like `hasClass`.
- [x] `.hasName()` returns true/false if name exists. Should take `options` like `hasClass`.
- [x] .`isType()` takes a string and returns true/false if the element is the given value (better name?)

To make this happen, I think it would be nice to also have some additional methods.
- [x] ~~`.getContent()` returns the content. Up for discussion... if it's array, it may be nice to return a collection element. This is people are not working directly with `content` property, which we should consider private.~~
- [x] ~~`.children()`with no condition returns a collection of of the content. This is essentially `.getContent()`~~
- [x] `.first()` returns `.get(0)`
- [x] `.second()` returns `.get(1)`

**Comment by danielgtaylor** [comment]
I think overall this is a good idea. Some notes:
1. Do you want to add a `.last()` (i.e. `this.get(this.length - 1)`)?
2. I'm a little concerned about name collisions in the work I've been doing on [fury](https://github.com/apiaryio/fury.js/blob/master/src/refract/api.es6#L33-L47). There you can see that I'm adding convenience getters/setters for a bunch of stuff. Now I'm wondering if that's still the right approach as we add more and more to the element base classes.

**Comment by smizell** [comment]
> Do you want to add a .last() (i.e. this.get(this.length - 1))?

Sounds good to me!

> I'm a little concerned about name collisions

Actually, a good concern. My vote would be to work hard to make the Minim API the best and then try to conform to it. We can find these kind of convenience methods to put into it when applicable while trying not to pollute the namespace too much.

And it made me think of a possible solution. Since `meta` is reserved for Refract, we have knowledge of what may be there. This means we could always use `meta` as refracted.

``` javascript
// Getters and setters
element.meta.set('id', 'my-id');
element.meta.get('id');

// Other elements
element.meta.get('title');
```

This makes for one interface to meta object. Now my question is, what is the better route to take?

``` javascript
// Get and test in same function
element.meta.contains('class', 'some-class');
element.meta.contains('class', 'some-class', 'and-another');

// Get first, then test
element.meta.get('class').has('some-class');

// Get and test in same function (would be actual code for get and test in same function)
element.meta.equals('id', 'my-id', andSomeValue);
element.meta.notEquals('id', 'not-the-id');

// Get first, then test
element.meta.get('id').toValue() === 'my-id';
```

This could simplify a lot of things doing it where getting and testing are in the same function.

``` javascript
// Basically findByClass() (which I didn't include above)
element.find(element => element.meta.contains('class', 'my-class'));

// Basically filterByClass()
element.filter(element => element.meta.contains('class', 'my-class'));
```

But it does create extra functions that already have meaning in JavaScript.

Thoughts? I'm really fine either way.

**Comment by smizell** [comment]
@danielgtaylor Still thinking about this. Getting into working with Fury today and see you have put things like title and description as getters/setters on your classes. Think this should be the norm rather than accessing through `meta`?

One thing to remember in this is that we want people to access Refract through things like Minim rather than interact directly with the JSON. So if we can find things to simplify like this, it will be way better.

**Comment by smizell** [comment]
I've crossed out the methods that I won't be implementing this go around.

**Comment by danielgtaylor** [comment]
@smizell 

> Getting into working with Fury today and see you have put things like title and description as getters/setters on your classes. Think this should be the norm rather than accessing through meta?

From the standpoint of a tooling author I do not (and should not) care where a title comes from. An API has a title. A resource has a title. I should be able to have a resource element and access `resource.title`. Of course we need to balance this with implementation details and the refract format complexity, but we should keep in mind and advocate for the end consumer. Ideally there are things they should just not need to worry about, like typing `resource.meta.title.toValue()` or `resource.attributes.href.toValue()` instead of just getting the title: `console.log(resource.title, resource.href);`.

Every extra step and new thing to memorize is a barrier to the newcomer and will slow down how quickly you can write tools for the format, plus it makes debugging and maintenance more difficult.

**Comment by smizell** [comment]
@danielgtaylor I don't see anything wrong with putting meta attributes onto the element (e.g. like you said `el.title`). 

When you access `el.title`, should it return a minim string instance or the value of that string? I think we can make the values accessible with `el.meta.title` still, but provide these convenience getters. Thoughts?
