### ISSUE TITLE
Handling null or undefined content

### ISSUE THREAD

**Issue by smizell** [refractproject/minim#36]
What do we do when we receive:
- Null values for types in JSON
- Undefined values for elements
- Incorrect types as values

**Comment by smizell** [comment]
See also https://github.com/refractproject/minim/issues/68

**Comment by kylef** [comment]
@smizell I am not sure if this situation got any better but I haven't hit many issues. I suspect problems serialising and deserialising should have gone away. Do you recall any specific examples that need fixing?
