### ISSUE TITLE
Minim 1.0 Proposal

### ISSUE THREAD

**Issue by smizell** [refractproject/minim#41]
This writeup outlines some ideas and thoughts on bringing Minim to a stable 1.0 release. I would like to work on stabilizing the interface and get some good use out of it before moving to 1.0, but would also like to not spend forever in pre-1.0 versions. 
## Aligning Minim with Refract

Right now, we call elements as types, such as `StringType`, `NumberType`, etc. We should align the naming of these to be `StringElement`, `NumberElement`, etc.

This goes for places where we call things "DOM." 
## Better Class Support for Non-ES6 Platform

Right now, to extend a class, you must be using ES6 or use a separate library for extending the prototype. I believe this is less than optimal, as it is a very important aspect of creating new elements. We need to think through how to provide support for this.

Backbone.js models extend models by adding a custom extend method on to classes [0]. They actually extend these classes using the underscore extend function.

Here is an example of a class in Backbone.js being extended.

``` javascript
_.extend(Model.prototype, Events, {
  foo: function() { return 'bar'; }
}
```

Model then provides a special extend method for extending that particular class with conventions such as:

``` javascript
var Book = Backbone.Model.extend({
  foo: function() { return 'hello world'; }
});
```

Now `Book` has all of the methods that `Model` has, but has a different `foo` method attached to the prototype. 

**I believe we should support extending classes this way, but it provides issues**. For instance, how can this extend override the constructor for an ES6 class? How can we provide a super for those using ES5? It brings with it the question, should we be doing all of this in ES5 (yikes)? I believe we can do everything here in ES5 that we need without the ES6 syntax.

No matter what direction we take, I believe extending a class in ES6 will still work correctly, even if we use ES5.
## Meta and Attributes as Minim Objects

Right now, the interface to meta is that it is a pseudo Minim Object that provides defaults for each of the values. Right now, you have a different interface to meta and attributes, as meta has a Minim interface and attributes is a simple object.

As Daniel [pointed out](https://github.com/refractproject/minim/issues/40), this pseudo Minim Object for meta creates some undesired effects. We need to solve this, which I belive takes:
- We need to lazy load meta and attributes since it would create an infinite loop
- We need to make meta and attributes Minim Objects
- We need to be able to provide default values so the user does not have to set things like id or class. They should always be there and the user should not have to check. This would also be helpful for providing defaults for attributes.
## Content as Minim Type

It would be helpful to store the content in a normal array, but provide a Minim instance for accessing the content. This means that meta, attributes, and content will all have the same interface.
## Object Property Setter

Setters for objects currently require two arguments—a property name and a value for that property. Backbone.js allows for providing an object directly to set. 

``` javascript
obj.set({ foo: 'bar' });
```

This would be really nice to support, and would be very similar to Backbone.js as a common convention.
## Better Output of Full Refract

Right now, outputing full refract will always output meta and attributes. It would be beneficial in reducing size to only output meta and attributes if they have properties set. Since we will be (hopefully) be setting these as Minim Objects, it may be helpful to add an `isEmpty` method to determine if the contents are empty.
## Handling Null Values

We need to handle `null` and `undefined` values better when parsing a Refract tree. For example, when the `value` of a `MemberType` is undefined, we should determine how to treat those values values. Same goes for `StringType` instances where the value is `null`.
## Conclusion

There are [more issues](https://github.com/refractproject/minim/issues) than outlined here, but these are the big ones. I would like to tackle these first and we can evaluate afterwards.

[0] I know JavaScript before ES6 didn't have classes, but it's the language we use.

**Comment by smizell** [comment]
cc @danielgtaylor

**Comment by danielgtaylor** [comment]
:+1: Great stuff!

My only comment is regarding ES6/ES5 classes and how to handle them. I am _strongly_ in favor of using ES6 classes, defaulting to ES6 in examples, and generally recommending people use ES6 inheritance if possible. We **should** also document how to use ES5 if it isn't possible.

The `_.extend` syntax is interesting but note that you can also do it by hand, _and_ you can simulate `super` calls easily. I'm definitely open to sugar wherever possible, but here's a quick sugarless example showing how it can work:

``` js
// This is our base class, defined in ES6
class MyObject {
  constructor(id) {
    this.id = id;
  }

  hello() {
    return `Hello, id ${this.id}!`;
  }

  bye() {
    return 'Goodbye!';
  }
}

// Now, let's pretend we have to use ES5
function MySubClass(id, name) {
  // Simulate a super call
  MyObject.bind(this)(id);
  this.name = name;
}

// Make it a subclass by copying the prototype
MySubClass.prototype = Object.create(MyObject.prototype);

// Now we can overwrite any methods we like
MySubClass.prototype.hello = function hello() {
  return `Hello, ${this.name}! (id:${this.id})`;
};

const test = new MySubClass(1, 'world');
console.log(test.hello());
// => Hello, world! (id:1)
console.log(test.bye());
// => Goodbye!
```

Hopefully this shows that we really don't need to move away from ES6 classes. You can run the above via `babel-node classtest.es6`.

**Comment by smizell** [comment]
Good stuff, and great example. I want to say I'm _very_ torn on this. I totally prefer the ES6 syntax for classes, but here are my current issues. I believe there are issues for users and **big** issues for developers.

First, the issues for users of the library. I'm assuming that a majority of people will not being using ES6. We won't want to require people to subclass like you've shown above, so we'll have to provide something like `StringElement.extend`. So now we have to support this forever, basically, unless we want to stop supporting ES5 at some point.

Whether we provide this in an ES6 class system or have it in ES5, we are not preventing the user from using it with ES6 classes. Take for instance [this article](http://mikefowler.me/2014/06/11/backbone-with-es6/) where the user is using ES6 classes with Backbone "classes." It is still usable and is transparent.

Now if we stopped here with the issues, I would see no big difference in writing Minim in ES6 and adding this special extend method for classes and would 100% vote for that. But the problem with working with this trickles down to the developer in a big way.  I have actually been quite frustrated with using ES6 for this library.
- Running tests takes at least five seconds each time. One second is devoted to linting, and the rest to transpiling. This is unbearable to me. I should be able to run my tests with nodemon or something and they finish by the time I glance at my terminal.
- No source maps, so errors in failing tests provide little help. The code Babel produces is unreadable to me.
- Related: I am fearful of supporting this library. If a user opens an issue saying they got an error on such and such line number, I will have to dig through two codebases... the transpiled and the ES6. If I don't now why the error is happening, it may be because of Babel magic.
- Code coverage tools provide incorrect data since they run against transpiled code. It's not even useful to look at it! Those tools are for helping you know what you haven't tested, and that data isn't there.
- I wanted to try out Flow, and it doesn't work for the new `for` loops in ES6 along with files ending in `.es6`. I switched to `.js`, but I get errors when I ran it because of the loops. This made Flow not really helpful.

With these things in mind, the development process for Minim is quite bad, especially for such a small library. The only win I see us getting here is nicer syntax. There is no reason users of the library couldn't use it with ES6, so we are OK there. And if we write this using old ES5 "classes," we can still use it on future platforms that support ES6, even with ES6 classes. Lastly, we'll always have to support this special `.extend` functionality, so there is no getting away from it.

---

Hopefully this doesn't seem like a rant (maybe a partial one). I am just struggling to seeing the benefit of using ES6 for a library like this with all of this pain I'm having. For the browser, it makes total sense because you will always have a build step. With this, the build step is unecessary. What are your thoughts on this? @danielgtaylor

**Comment by smizell** [comment]
Writing this with prototypical inheritance is also still usable with CoffeeScript classes.

``` coffeescript
MyClass = (@id, @name) ->

MyClass::hello =  -> return "Hello, #{@name} with id #{@id}"

class MySubClass extends MyClass

test = new MySubClass 1, 'John'
console.log test.hello() # Hello, John with id 1
```

Also, wanted to make a quick comment on this:

> You can run the above via `babel-node classtest.es6`

This actually will transpile then run your code. Babel-node takes 0.6 seconds to run the code below :)

``` js
console.log('Hello world');
```

Node 0.12 takes 0.043 seconds.

**Comment by danielgtaylor** [comment]
Love the rant - get it all out! :facepunch: 

First, are you suggesting we rewrite in vanilla ES5? It seems like many of these issues are going to be problem with _any_ transpiled language, including CoffeeScript (though to a lesser degree).

> we'll have to provide something like StringElement.extend. So now we have to support this forever, basically, unless we want to stop supporting ES5 at some point.

It could maybe be an extra module that you load to provide compatibility. If and when ES6 becomes the norm we could phase it out without a major version bump in Minim:

``` js
var minim = require('minim');
minim.use(require('minim-extend'));
```

Yes, in the short term it's still something we will maintain, and we would need to think about how best to test it to make sure we never break compatibility, but it gives us a path to not maintain it forever. Just a thought.

> Running tests takes at least five seconds each time. One second is devoted to linting, and the rest to transpiling. This is unbearable to me. I should be able to run my tests with nodemon or something and they finish by the time I glance at my terminal.

This has really frustrated me too. What's happening is that we are spawning `node`, loading `npm`, spawning `node` again, loading `eslint`, running it, spawning `node` again, loading `babel`, etc etc. The biggest offender by far though is `babel` itself. I just hacked up a quick Gulpfile to try it there and that shaves off about a couple seconds, but it's still fairly slow. One thing that would make it much faster is adding a watch command (saving startup time of a couple seconds). Here's me file if you want to play with it:

``` js
var gulp = require('gulp');
var eslint = require('gulp-eslint');
var babel = require('gulp-babel');
var mocha = require('gulp-mocha');

gulp.task('compile', function () {
  return gulp.src(['src/**/*.es6'])
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failOnError())
    .pipe(babel())
    .pipe(gulp.dest('lib'));
});

gulp.task('default', ['compile'], function () {
  require('babel/register');
  gulp.src(['test/**/*.es6'])
    .pipe(mocha());
});
```

> No source maps, so errors in failing tests provide little help. The code Babel produces is unreadable to me.

Both Babel and `gulp-babel` provide a source map option. We should try it out, but I don't have much experience with source maps honestly.

> Related: I am fearful of supporting this library. If a user opens an issue saying they got an error on such and such line number, I will have to dig through two codebases... the transpiled and the ES6. If I don't now why the error is happening, it may be because of Babel magic.

Is the location fixed by generating source maps? One option we have here is to remove any features that require the `babel-runtime` (like `Symbol`) and then each file will have a bit of code dumped in the top to handle whatever features that file is using. It's similar to how CoffeeScript handles it, but I'll warn you it is a bunch of difficult to read code. If we don't use the runtime then _all_ the code run by our downstream is in our lib folder, which may have some advantages. Still not perfect though, and it'll duplicate a lot of code.

> Code coverage tools provide incorrect data since they run against transpiled code. It's not even useful to look at it! Those tools are for helping you know what you haven't tested, and that data isn't there.

Do source maps fix this one too? I know it was possible with CoffeeScript with some magic - maybe we can figure out something for this.

> I wanted to try out Flow, and it doesn't work for the new for loops in ES6 along with files ending in .es6. I switched to .js, but I get errors when I ran it because of the loops. This made Flow not really helpful.

Does Flow not have these same issues if you annotate with types? Or do you plan to keep vanilla JS and just run Flow on that?

> You can run the above via babel-node classtest.es6

Yeah it's just a quick way to run some ES6 without having to compile, then run as two steps. It's slow but convenient when testing stuff out. :smile:

---

Anyway, you make some good points and I'm not totally against using ES5. I was hoping that we could make ES6 work and use this project as a small example for future projects. I agree that some of these issues are a pain, but I hope that maybe we can figure out a way to make it work. We can't be the first people running into this!

**Comment by smizell** [comment]
Woah, awesome response. It's late here but wanted to note a couple of things. 

First, I'm suggesting we consider ES5 for this library. Not necessarily saying we should at this point, but it solves all of the problems I outlined. 

Second, I think ES6 is catching on in the browser because you always have a build step and need source maps. Server side code seems like a different problem area, which makes me wonder if people are using ES6 this way. 

Last, I had planned on just running flow on top of the code to get make sure there weren't any compile time type issues. Would want to add another build step back in.

**Comment by smizell** [comment]
Closing, as most of these are addressed or captured in other issues.
