### ISSUE TITLE
Handle elements inside attributes better

### ISSUE THREAD

**Issue by smizell** [refractproject/minim#50]
Is there a way we can handle elements inside of attributes better. The current way seems tied directly to one use case, where a property at the root of the object is an element.
- Have a `preToRefract` hook? 
- Have a `preAttributeConvert` hook?

Then we leave it up to the user to decide how this works in those methods.

**Comment by smizell** [comment]
With embedded Refract, this is covered. You can check for the presence of `_refract` to know what has been refracted.

The only caveat is a situation where some element in attribute is a different element other than the primitive elements and does **not** contain any Refract data in the `_refract` object. In this situation, you need some domain knowledge.

But in this case, you can know what has or has not been refracted.

**Comment by kylef** [comment]
I am not entirely sure what this is, but I think it may not be relevant anymore with the stricter JSON Refract serialisation rules in Refract 1.0. @smizell Is there anything left to action here?
