### ISSUE TITLE
Better handling of undefined

### ISSUE THREAD

**Issue by danielgtaylor** [refractproject/minim#68]
This is a fun experiment:

``` js
el = new minim.ObjectElement({a: 1});

// This works
el.toRefract();

// This fails
el.set('a', undefined);
el.toRefract(); // => throws exception

// Also this one is fun
el = new minim.ArrayElement([1, undefined]);
el.findByElement('test'); // => throws exception
```

Lots of other stuff falls down like this too. Question: should `forEach` be returning undefined items? What about for an object where the key is defined but the value is undefined? Is this just something that we need to check for in most of the convenience methods?

How would you run into this? I had some malformed serialized refract which I loaded and it wound up having undefined keys and values for object elements. Any searching that included those elements wound up throwing exceptions.

**Comment by kylef** [comment]
Lots of cases where undefined is expected have been handled now: https://github.com/refractproject/minim/pull/272 https://github.com/refractproject/minim/pull/268 https://github.com/refractproject/minim/pull/258 https://github.com/refractproject/minim/pull/205
