### ISSUE TITLE
Merge dredd-transactions' refract.coffee with Minim

### ISSUE THREAD

**Issue by honzajavorek** [refractproject/minim#99]
When implementing `dredd-transacitons`, I made my own implementation of a small Refract library on top of `traverse` and `sift`, because neither `refract-query` or `minim` seemed to solve my problems. It lives in `refract.coffee` file, hence the name in the title of this issue.

I wrote down rough list of requirements I expect from a Refract library: https://github.com/apiaryio/dredd-transactions/issues/10

**Comment by kylef** [comment]
I think this one has been tackled, please re-open if I am incorrect.

**Comment by honzajavorek** [comment]
Only once https://github.com/apiaryio/dredd-transactions/pull/101 gets merged. You're ahead! 😛 But you're right the issue is about minim supporting the things I had in the file, and that has been done.
